redcell<-read.table("redcell.txt", header=T)
names(redcell)
redcell$ventilation<-factor(redcell$ventilation)
is.factor(redcell$ventilation)
plot(folate~ventilation, data=redcell)
model<-lm(folate~ventilation, data=redcell)
summary(model)